# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExifViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExifViewer(object):
    def setupUi(self, ExifViewer):
        ExifViewer.setObjectName("ExifViewer")
        ExifViewer.resize(520, 400)
        ExifViewer.setMinimumSize(QtCore.QSize(500, 400))
        ExifViewer.setStyleSheet("background-color: #c3fdff;")
        self.gridLayout = QtWidgets.QGridLayout(ExifViewer)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_tab = QtWidgets.QTabWidget(ExifViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_tab.sizePolicy().hasHeightForWidth())
        self.widget_tab.setSizePolicy(sizePolicy)
        self.widget_tab.setStyleSheet("")
        self.widget_tab.setObjectName("widget_tab")
        self.general_details_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_details_tab.sizePolicy().hasHeightForWidth())
        self.general_details_tab.setSizePolicy(sizePolicy)
        self.general_details_tab.setStyleSheet("background-color: #eeffff;")
        self.general_details_tab.setObjectName("general_details_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.general_details_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.general_details_data = QtWidgets.QTreeWidget(self.general_details_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_details_data.sizePolicy().hasHeightForWidth())
        self.general_details_data.setSizePolicy(sizePolicy)
        self.general_details_data.setStyleSheet("")
        self.general_details_data.setObjectName("general_details_data")
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.general_details_data.headerItem().setFont(0, font)
        self.general_details_data.header().setVisible(True)
        self.general_details_data.header().setCascadingSectionResizes(False)
        self.gridLayout_2.addWidget(self.general_details_data, 0, 0, 1, 1)
        self.widget_tab.addTab(self.general_details_tab, "")
        self.exif_details_tab = QtWidgets.QWidget()
        self.exif_details_tab.setStyleSheet("background-color: #eeffff;")
        self.exif_details_tab.setObjectName("exif_details_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.exif_details_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.exif_details_data = QtWidgets.QTreeWidget(self.exif_details_tab)
        self.exif_details_data.setStyleSheet("")
        self.exif_details_data.setObjectName("exif_details_data")
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exif_details_data.headerItem().setFont(0, font)
        self.exif_details_data.header().setVisible(False)
        self.exif_details_data.header().setCascadingSectionResizes(False)
        self.exif_details_data.header().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.exif_details_data, 0, 0, 1, 1)
        self.widget_tab.addTab(self.exif_details_tab, "")
        self.gridLayout.addWidget(self.widget_tab, 0, 0, 1, 1)

        self.retranslateUi(ExifViewer)
        self.widget_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ExifViewer)

    def retranslateUi(self, ExifViewer):
        _translate = QtCore.QCoreApplication.translate
        ExifViewer.setWindowTitle(_translate("ExifViewer", "Image Details"))
        self.general_details_data.headerItem().setText(0, _translate("ExifViewer", "Data"))
        self.widget_tab.setTabText(self.widget_tab.indexOf(self.general_details_tab), _translate("ExifViewer", "General Details"))
        self.exif_details_data.headerItem().setText(0, _translate("ExifViewer", "Data"))
        self.widget_tab.setTabText(self.widget_tab.indexOf(self.exif_details_tab), _translate("ExifViewer", "Exif Details"))
